# Generated by Django 5.0.1 on 2024-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedimage',
            name='image',
            field=models.ImageField(upload_to='frontend/build/images/'),
        ),
    ]
