# Generated by Django 5.0.1 on 2024-01-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_analyzedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedimage',
            name='image',
            field=models.ImageField(upload_to='images/images/'),
        ),
    ]
