# Generated by Django 5.0.1 on 2024-01-05 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_analyzedimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
